// <auto-generated />
namespace liftmarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v40 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v40));
        
        string IMigrationMetadata.Id
        {
            get { return "202101060244121_v4.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
